#!/bin/sh

VOLUME=${VOLUME:-/mirror}
ALLOW=${ALLOW:-192.168.0.0/16 172.16.0.0/12}
OWNER=${OWNER:-nobody}
GROUP=${GROUP:-nogroup}

chown "${OWNER}:${GROUP}" "${VOLUME}"

[ -f /etc/rsyncd.conf ] || cat <<EOF > /etc/rsyncd.conf
uid = ${OWNER}
gid = ${GROUP}
use chroot = yes
log file = /dev/stdout
reverse lookup = no

[volume]
    hosts deny = *
    hosts allow = ${ALLOW}
    read only = false
    path = ${VOLUME}
    comment = docker volume
EOF

[ -f /etc/nginx/conf.d/default.conf ] || cat <<EOF > /etc/nginx/conf.d/default.conf
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  # Everything is a 404
  root ${VOLUME};

  $(for a in ${ALLOW}; do echo "allow ${a};"; done)
  deny all;

  autoindex on;
  access_log /dev/stderr;
  error_log /dev/stdout;
}
EOF

rsync --no-detach --daemon --config /etc/rsyncd.conf &
nginx -g 'daemon off; pid /run/nginx.pid;' &

trap "killall rsync nginx" QUIT TERM

wait
